### ISSUE TITLE
[Epic] Milestone 1

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/Web3ModalFlutter#1]
## Implementation Path
This is intended as an overview of critical path work for the Web3Modal Flutter SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### Features
- [x] Show mobile wallets list from Explorer API
- [x] Show QR Code
- [x] Customizable cloud PROJECT_ID
- [x] Connect with Wallet
- [x] Add Eth_methods to example
- [x] Reuse session
- [x] Add “What is a wallet” screen
- [x] Add docs to https://docs.walletconnect.com/2.0/
- [x] https://github.com/WalletConnect/Web3ModalFlutter/issues/3
- [ ] ~~Add contract methods to example~~
- [x] [explorerRecommendedWalletIds](https://docs.walletconnect.com/2.0/web3modal/options#explorerrecommendedwalletids-optional)
- [x] [explorerExcludedWalletIds](https://docs.walletconnect.com/2.0/web3modal/options#explorerexcludedwalletids-optional)
- [x]  Improve Animations + UI

### Next steps
https://github.com/WalletConnect/Web3ModalFlutter/issues/2
