### ISSUE TITLE
Migrate Web3Modal to new v3 styles and de-couple it completely from WalletConnectModalFlutter package

### ISSUE THREAD

**Issue by quetool** [WalletConnect/Web3ModalFlutter#18]
We want to change the style of current Web3Modal and migrate it to v3 Design while at the same time removing completely the dependency from WalletConnectModal as they should be 2 separate packages
```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/Web3ModalFlutter/pull/17
- [x] Step 2: Create new widgets on Web3Modal repositoty following v3 style guide and stop using WallectConnectModal widgets
- [x] Step 3: Remove completely the UI dependency from WalletConnectModal and tests everything
- [ ] Step 4: Migrate to new API instead of Explorer API
- [ ] Step 5: Migrate all business logic and remove completely the business logic dependency from WalletConnectModal
```
