### ISSUE TITLE
[Epic] Milestone 2

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/Web3ModalFlutter#2]
## Implementation Path
This is intended as an overview of critical path work for the Web3Modal Flutter SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

### Features

- [x] Account view
- [x] Show balance in Account view
- [x] Show chain info in Account view
- [x] Adapt views to Light/Dark theme mode
- [x] Show errors/messages in internal toasts
- [x] Improve Connect Button
- [x] Chain select in Account View
- [x] Update docs

### Next steps
TBD
